### ISSUE TITLE
Exponential number of new bot accounts

### ISSUE THREAD

**Issue by kantackistan** [randomouscrap98/sbs-rust-contentapi#95]
Just a heads up, a _lot_ of bot accounts are being generated. And with increasing frequency:

https://smilebasicsource.com/activity

**Comment by randomouscrap98** [comment]
thanks for the heads up!

I've gone ahead and implemented two things:
* Users who have not completed registration are now filtered from the activity list (none of those accounts completed their registration, so they're all hidden now)
* Registration is now manually approved instead of automatically sending out the code. It's a bit of a hassle, I know, but we get so few REAL accounts, I think it'll be fine.
